config/routes.rb
Rails.application.routes.draw do

  root 'abbrv8_url#index'

  resources :abbrv8_url
  
  get 'stats' => 'abbrv8_url#stats', as: :stats
  get ':short_url' => 'abbrv8_url#go_to_short_url', as: :short

end

app/models/abbrv8_url.rb
class Abbrv8Url < ActiveRecord::Base
  validates :long_url, presence: true, allow_blank: false
  validates :short_url, uniqueness: true, allow_blank: false
  validates_formatting_of :long_url, using: :url

  before_validation :standardize_long_url, :generate_short_url

  has_many :visits 

  def standardize_long_url
    unless self.long_url[0..6] == "http://" || self.long_url[0..7] == "https://"
      self.long_url = "http://" + self.long_url
    end
  end

  def generate_short_url
    begin
      random_string = /\d|\w{5}/.gen
    end while Abbrv8Url.where(short_url: random_string).any?

    self.short_url = random_string
  end

  def self.error_message
    case rand(5)
    when 0
      "Seriously?"
    when 1
      "Um...are you sure you typed that right?"
    when 2
      "That doesn't look like a url to me.  But then what do I know, I'm just the internet..."
    when 3
      "Nope."
    when 4
      "LOL nice try"
    end
  end
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :abbrv8_url
end

app/controllers/abbrv8_url_controller.rb
class Abbrv8UrlController < ApplicationController
  def index
  end

  def create
    abbrv8_url = Abbrv8Url.create(long_url: params[:abbrv8_url][:long_url])
 
    if abbrv8_url.errors.empty?
      @short_url = short_url(abbrv8_url.short_url) 
    else
      @error_messages = abbrv8_url.errors.full_messages << Abbrv8Url.error_message
    end

    render action: :index
  end

  def go_to_short_url
    abbrv8_url = Abbrv8Url.where(short_url: params[:short_url]).first

    if abbrv8_url
      abbrv8_url.visits << Visit.create
      redirect_to abbrv8_url.long_url
    else
      redriect_to action: :index
    end
  end

  def stats
    @abbrv8_urls = Abbrv8Url.all.includes(:visits).order('visits.created_at desc')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/abbrv8_url/index.html.haml
=link_to "Stats", stats_path

#container
  #title
    Abbrv8

  #shorten-form
    = form_for :abbrv8_url, url: {action: 'create'} do |f|
      .text-box
        = f.text_field :long_url
      .button
        = f.submit "Shorten"

  #short-url= link_to(@short_url, @short_url, target: "_blank") unless @short_url.blank?

  #errors
    - if @error_messages
      - @error_messages.each do |message|
        .message= message

app/views/abbrv8_url/stats.html.haml
=link_to "< Back", root_path

#title
  Stats

#stats
  .row
    .col
      Short
    .col
      Long
    .col
      \# of Visits
  - @abbrv8_urls.each do |abbrv8_url|
    .row
      .col= link_to(short_url(abbrv8_url.short_url), short_url(abbrv8_url.short_url), target: "_blank")
      .col= link_to(abbrv8_url.long_url, abbrv8_url.long_url, target: "_blank")
      .col= abbrv8_url.visits.count

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abbrv8</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>